// Generated by genversion.
export const version = `0.0.1`
export const name = `maren`
export const license = `Apache-2.0`
export const description = `A nestjs server for Boliden`
export const author = { name: `carddamom`, email: `carddamom@tutanota.com` }
